# Generated by Django 5.0.3 on 2025-10-30 12:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='issued_at',
            new_name='issue_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='template_text',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
