# Generated by Django 5.0.3 on 2025-10-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_id',
        ),
    ]
