# Generated by Django 5.0.3 on 2025-11-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='coach_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='full_name',
        ),
    ]
