# Generated by Django 5.0.3 on 2025-11-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_certificate_coach_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(default='sara', max_length=255),
            preserve_default=False,
        ),
    ]
