# Generated by Django 5.2.7 on 2025-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_reviewphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='watched_video_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of watched video IDs'),
        ),
    ]
