# Generated by Django 5.0.3 on 2025-11-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_reviewphoto'),
        ('courses', '0011_certificate_coach_name_certificate_full_name'),
    ]

    operations = [
    ]
