# Generated by Django 5.0.3 on 2025-11-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_enrollment_watched_video_ids'),
        ('courses', '0012_merge_20251118_1432'),
    ]

    operations = [
    ]
