# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_merge_20251118_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading thumbnail file', null=True),
        ),
    ]
