# Generated by Django 5.2.7 on 2025-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_in_days',
            field=models.PositiveIntegerField(default=1, help_text='Course duration in days for progress calculation'),
        ),
    ]
