# Generated by Django 5.0.3 on 2025-11-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_enrollment_watched_video_ids'),
        ('courses', '0013_course_thumbnail_url'),
    ]

    operations = [
    ]
