# Generated by Django 5.0.3 on 2025-11-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_enrollment_watched_video_ids'),
        ('courses', '0014_course_duration_in_days'),
    ]

    operations = [
    ]
