# Generated by Django 5.0.3 on 2025-11-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_pdf_pdf_file'),
        ('courses', '0017_course_is_free'),
    ]

    operations = [
    ]
