# Generated by Django 5.0.3 on 2025-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
